function output = savedialog(algorithm)

d = dialog('Position',[600 400 250 200],'Name','Ergebnisse Speichern');

text = uicontrol('Parent',d,...
       'Style','text',...
       'Position',[20 150 210 30],...
       'String',['Möchtest du die Ergebnisse von ' algorithm ' speichern?']);

checkbox = uicontrol('Parent',d,...
       'Style','checkbox',...
       'Position',[20 110 100 20],...
       'String','Favorit');
 
note = uicontrol('Parent',d,...
       'Style','edit',...
       'Max',3,'Min',1,...
       'Position',[20 50 210 60]);

ok = uicontrol('Parent',d,...
   'Style','pushbutton',...
   'Position',[70 20 40 20],...
   'String','Ok',...
   'Callback',@confirm);

cancel = uicontrol('Parent',d,...
   'Style','pushbutton',...
   'Position',[140 20 40 20],...
   'String','Nein',...
   'Callback','delete(gcf)');

output = struct('confirm','no');
% Wait for d to close before running to completion
uiwait(d);

   function confirm(popup,event)
      output = struct('confirm','yes','favorite',checkbox.Value,...
                      'note',note.String);
      delete(d);
   end

end