%% Load mat file
var = 'hdmdresult';
data = load('C:\Users\bouaz\Desktop\Thesis-Tex\Inhalt\2_Ergebnisse\_Resultate\Kapitel4\Duffing_Periodisch.mat',var);
data = data.(var);

%% Data
t = data{1,1}.t;
tobeshown = [1,2,3,8];
Y{1} = [data{1,1}.Ytrain, data{1,1}.Ytest];
Y{2} = [data{1,2}.Ytrain, data{1,2}.Ytest];
Y{3} = [data{1,3}.Ytrain, data{1,3}.Ytest];

for i = 1:length(tobeshown)
    j = tobeshown(i);
    Y1{i} = [data{1,3*j-2}.Yr, data{1,3*j-2}.Yp];
    Y2{i} = [data{1,3*j-1}.Yr, data{1,3*j-1}.Yp];
    Y3{i} = [data{1,3*j}.Yr, data{1,3*j}.Yp];
end

%% . Save as tikz
pgfplot(t,Y{1},'Soll',...
    t,Y1{1},'$d=1$',...
    t,Y1{2},'$d=2$',...
    t,Y1{3},'$d=4$',...
    t,Y1{4},'$d=24$','4_duffing_signalx1','C:\Users\bouaz\Desktop\Thesis\pics');
pgfplot(t,Y{2},'Soll',...
    t,Y2{1},'$d=1$',...
    t,Y2{2},'$d=2$',...
    t,Y2{3},'$d=4$',...
    t,Y2{4},'$d=24$','4_duffing_signalx2','C:\Users\bouaz\Desktop\Thesis\pics');
pgfplot(t,Y{3}(1,:),'Soll',...
    t,Y3{1}(1,:),'$d=1$',...
    t,Y3{2}(1,:),'$d=2$',...
    t,Y3{3}(1,:),'$d=4$',...
    t,Y3{4}(1,:),'$d=24$','4_duffing_signalx_1','C:\Users\bouaz\Desktop\Thesis\pics');
pgfplot(t,Y{3}(2,:),'Soll',...
    t,Y3{1}(2,:),'$d=1$',...
    t,Y3{2}(2,:),'$d=2$',...
    t,Y3{3}(2,:),'$d=4$',...
    t,Y3{4}(2,:),'$d=24$','4_duffing_signalx_2','C:\Users\bouaz\Desktop\Thesis\pics');
