function config = simconfig()

%% Display Tool logo in command window
disp('#######################################');
disp('#                                     #');
disp('#     Koopman Identification Tool     #');
disp('#                                     #');
disp('#######################################');

%% Define mode of usage
config.general.usage = 'new'; % archive

%% Define path to access all functions
addpath(genpath('C:\Users\bouaz\Desktop\Code\Matlab'));

%% Define ARCHIVE path for storing and loading data
config.general.archivepath = 'C:\Users\bouaz\Desktop\Thesis-Tex\Inhalt\2_Ergebnisse\1_Daten\';
config.general.plotpathtikz = 'C:\Users\bouaz\Desktop\Thesis-Tex\Inhalt\2_Ergebnisse\2_Plots\tikz\';
config.general.plotpathpng = 'C:\Users\bouaz\Desktop\Thesis-Tex\Inhalt\2_Ergebnisse\2_Plots\png\';

%% Define FOLDERNAME acronyms
config.general.folderacr = struct('algorithm','alg','system','sys','params','p','x0','x0',...
    'dt','dt','timesteps','ts','horizon','hrz','rank','r','delays','d','spacing','sp','measured','m','observables','obs');

%% Define ALGORITHMS struct with function
config.general.algorithms = struct('EDMD',@EDMD,'kDMD',@kDMD,'kDMDc',@kDMDc,...
    'HDMD',@HDMD,'HDMDc',@HDMDc,'BiHDMDc',@BiHDMDc,'HAVOK',@HAVOK,'HAVOKc',@HAVOKc,...
    'HAVOK_',@HAVOK_,'HAVOK__',@HAVOK__,'HAVOK___',@HAVOK___,'CONVCOORD',@CONVCOORD);

%% Define SYSTEMS struct with acronym and function
config.general.systems = ...
    struct('lorenz',struct('acr','LR','fun',@lorenz),...
           'duffing',struct('acr','DF','fun',@duffing),...
           'roessler',struct('acr','RL','fun',@roessler),...
           'vanderpol',struct('acr','VDP','fun',@vanderpol),...
           'pendulum',struct('acr','PDL','fun',@pendulum),...
           'doubletank',struct('acr','DBLT','fun',@doubletank),...
           'trippletank',struct('acr','TRLT','fun',@trippletank),...
           'evaporationplant',struct('acr','EVP','fun',@evaporationplant),...
           'massoscillator',struct('acr','EMS','fun',@massoscillator),...
           'examplesys',struct('acr','EXM','fun',@examplesys),...
           'examplesys2',struct('acr','EXM2','fun',@examplesys2));
                       
%% Define PLOTS struct with name and function
config.general.plots = ...
    struct('phaseY',struct('name','Phasenraum','fun',@phaseplot,'args',{{'X','x'}},'loc','main'),...
           'phaseV',struct('name','Delay Phasenraum','fun',@phaseplot,'args',{{'V_','v'}},'loc','main'),...
           'disceig',struct('name','Diskr. Eigenwerte','fun',@disceigplot,'args',{{'d'}},'loc','main'),...
           'conteig',struct('name','Kontin. Eigenwerte','fun',@conteigplot,'args',{{'omega'}},'loc','main'),...
           'sing',struct('name','Singulärwerte','fun',@singplot,'args',{{'sn','sn_'}},'loc','main'),...
           'phasebasisY',struct('name','Phasenraum mit SVD Moden','fun',@phasebasisplot,'args',{{'X','V_'}},'loc','sec'),...
           'reconstructY',struct('name','Rekonstruktion','fun',@reconstructplot,'args',{{'Ytrain','Yr','RMSEYr','Ytest','Yp','RMSEYp','y'}},'loc','sec'),...
           'reconstructV',struct('name','Delay Rekonstruktion','fun',@reconstructplot,'args',{{'Vtrain','Vr','RMSEVr','Vtest','Vp','RMSEVp','v'}},'loc','sec'),...
           'reconstructW',struct('name','Conv. Rekonstruktion','fun',@reconstructplot,'args',{{'Wtrain','Wr','RMSEWr','Wtest','Wp','RMSEWp','w'}},'loc','sec'),...
           'rmseY',struct('name','rmse','fun',@rmseplot,'args',{{'rmseY'}},'loc','sec'),...
           'rmseV',struct('name','Delay rmse','fun',@rmseplot,'args',{{'rmseV'}},'loc','sec'),...
           'rmseW',struct('name','Conv. rmse','fun',@rmseplot,'args',{{'rmseW'}},'loc','sec'),...
           'matrix',struct('name','Koopmanoperator','fun',@matrixplot,'args',{{'A'}},'loc','sec'));
                     
%% Define general fieldnames
config.general.fieldnames.data = {'t','X','Y'};
config.general.fieldnames.metadata = {'note','favorite','date','time'};

%% Define EDMD struct
config.edmd.plots = {'phaseY','disceig','sing','conteig','reconstructY','rmseY','phasebasisY'};
config.edmd.fieldnames.input = {'algorithm','system','params','x0',...
    'dt','timesteps','horizon','rank','delays','spacing','measured','observables'};
config.edmd.fieldnames.svd = {'U_','s_','sn','sn_','V_'};
config.edmd.fieldnames.hankel = {'H'};
config.edmd.fieldnames.model = {'A','W','d','Phi','omega','Km',...
    'Ytrain','Yr','tr','RMSEYr','rmseYr','Ytest','Yp','tp','RMSEYp','rmseYp',...
    'RMSEY','rmseY'};

config.edmd.fieldnames.order = [config.edmd.fieldnames.input,config.general.fieldnames.data,...
    config.edmd.fieldnames.hankel,config.edmd.fieldnames.svd,config.edmd.fieldnames.model,...
    config.general.fieldnames.metadata];

%% Define kDMD struct
config.kdmd.plots = {'phaseY','disceig','sing','conteig','reconstructY','rmseY'};
config.kdmd.fieldnames.input = {'algorithm','system','params','x0',...
    'dt','timesteps','horizon','rank','delays','spacing','measured','kernel'};
config.kdmd.fieldnames.svd = {'U_','s_','sn','sn_'};
config.kdmd.fieldnames.hankel = {'H'};
config.kdmd.fieldnames.model = {'Atilde','W','d','Phi','omega','v',...
    'Ytrain','Yr','tr','RMSEYr','rmseYr','Ytest','Yp','tp','RMSEYp','rmseYp',...
    'RMSEY','rmseY'};

config.kdmd.fieldnames.order = [config.kdmd.fieldnames.input,config.general.fieldnames.data,...
    config.kdmd.fieldnames.hankel,config.kdmd.fieldnames.svd,config.kdmd.fieldnames.model,...
    config.general.fieldnames.metadata];

%% Define kDMDc struct
config.kdmdc.plots = {'phaseY','disceig','sing','conteig','reconstructY','rmseY'};
config.kdmdc.fieldnames.input = {'algorithm','system','params','x0','input',...
    'dt','timesteps','horizon','rank','delays','spacing','measured','kernel'};
config.kdmdc.fieldnames.svd = {'U_','s_','sn','sn_'};
config.kdmdc.fieldnames.data = {'U'};
config.kdmdc.fieldnames.hankel = {'H','Hu'};
config.kdmdc.fieldnames.model = {'Atilde','W','d','Phi','omega','v',...
    'Ytrain','Yr','tr','RMSEYr','rmseYr','Ytest','Yp','tp','RMSEYp','rmseYp',...
    'RMSEY','rmseY'};

config.kdmdc.fieldnames.order = [config.kdmdc.fieldnames.input,config.kdmdc.fieldnames.data,...
    config.general.fieldnames.data,config.kdmdc.fieldnames.hankel,config.kdmdc.fieldnames.svd,...
    config.kdmdc.fieldnames.model,config.general.fieldnames.metadata];

%% Define HDMD struct
config.hdmd.plots = {'phaseY','disceig','sing','conteig','reconstructY','rmseY','phasebasisY'};
config.hdmd.fieldnames.input = {'algorithm','system','params','x0',...
    'dt','timesteps','horizon','rank','delays','spacing','measured','observables'};
config.hdmd.fieldnames.svd = {'U_','s_','sn','sn_','V_'};
config.hdmd.fieldnames.hankel = {'H'};
config.hdmd.fieldnames.model = {'Atilde','W','d','Phi','omega','b','A',...
    'Ytrain','Yr','tr','RMSEYr','rmseYr','Ytest','Yp','tp','RMSEYp','rmseYp',...
    'RMSEY','rmseY'};

config.hdmd.fieldnames.order = [config.hdmd.fieldnames.input,config.general.fieldnames.data,...
    config.hdmd.fieldnames.hankel,config.hdmd.fieldnames.svd,config.hdmd.fieldnames.model,...
    config.general.fieldnames.metadata];

%% Define HDMDc struct
config.hdmdc.plots = {'phaseY','disceig','sing','conteig','reconstructY','rmseY','phasebasisY'};
config.hdmdc.fieldnames.input = {'algorithm','system','params','x0','input',...
    'dt','timesteps','horizon','rank','delays','uhasdelays','spacing','measured','observables'};
config.hdmdc.fieldnames.svd = {'U_','s_','sn','sn_','V_'};
config.hdmdc.fieldnames.data = {'U'};
config.hdmdc.fieldnames.hankel = {'H','Hu'};
config.hdmdc.fieldnames.model = {'Atilde','Btilde','W','d','Phi','omega','b','A','B',...
    'Ytrain','Yr','tr','RMSEYr','rmseYr','Ytest','Yp','tp','RMSEYp','rmseYp',...
    'RMSEY','rmseY'};

config.hdmdc.fieldnames.order = [config.hdmdc.fieldnames.input,config.general.fieldnames.data,...
    config.hdmdc.fieldnames.data,config.hdmdc.fieldnames.hankel,config.hdmdc.fieldnames.svd,...
    config.hdmdc.fieldnames.model,config.general.fieldnames.metadata];

%% Define BiHDMDc struct
config.bihdmdc.plots = {'phaseY','disceig','sing','conteig','reconstructY','rmseY','phasebasisY'};
config.bihdmdc.fieldnames.input = {'algorithm','system','params','x0','input',...
    'dt','timesteps','horizon','rank','delays','spacing','measured','observables'};
config.bihdmdc.fieldnames.svd = {'U_','s_','sn','sn_','V_'};
config.bihdmdc.fieldnames.data = {'U'};
config.bihdmdc.fieldnames.hankel = {'H','Hu'};
config.bihdmdc.fieldnames.model = {'Atilde','Btilde','W','d','Phi','omega','b',...
    'Ytrain','Yr','tr','RMSEYr','rmseYr','Ytest','Yp','tp','RMSEYp','rmseYp',...
    'RMSEY','rmseY'};

config.bihdmdc.fieldnames.order = [config.bihdmdc.fieldnames.input,config.general.fieldnames.data,...
    config.bihdmdc.fieldnames.data,config.bihdmdc.fieldnames.hankel,config.bihdmdc.fieldnames.svd,...
    config.bihdmdc.fieldnames.model,config.general.fieldnames.metadata];

%% Define HAVOK struct
config.havok.plots = {'phaseY','phaseV','sing','conteig','reconstructV','rmseV','matrix'};
config.havok.fieldnames.input = {'algorithm','system','params','x0',...
    'dt','timesteps','horizon','rank','delays','spacing','measured','observables'};
config.havok.fieldnames.svd = {'U_','s_','sn','sn_','V_'};
config.havok.fieldnames.hankel = {'H'};
config.havok.fieldnames.model = {'A','B','omega','d','Vtrain','Vr','tr','RMSEVr','rmseVr','Vtest','Vp','tp','RMSEVp','rmseVp',...
    'RMSEV','rmseV'};

config.havok.fieldnames.order = [config.havok.fieldnames.input,config.general.fieldnames.data,...
    config.havok.fieldnames.hankel,config.havok.fieldnames.svd,config.havok.fieldnames.model,...
    config.general.fieldnames.metadata];

%% Define HAVOK_ struct
config.havok_.plots = {'phaseY','phaseV','sing','conteig','reconstructV','rmseV','matrix'};
config.havok_.fieldnames.input = {'algorithm','system','params','x0',...
    'dt','timesteps','horizon','rank','delays','spacing','measured','observables'};
config.havok_.fieldnames.svd = {'U_','s_','sn','sn_','V_'};
config.havok_.fieldnames.hankel = {'H'};
config.havok_.fieldnames.model = {'A','B','omega','d','Vtrain','Vr','tr','RMSEVr','rmseVr','Vtest','Vp','tp','RMSEVp','rmseVp',...
    'RMSEV','rmseV'};

config.havok_.fieldnames.order = [config.havok_.fieldnames.input,config.general.fieldnames.data,...
    config.havok_.fieldnames.hankel,config.havok_.fieldnames.svd,config.havok_.fieldnames.model,...
    config.general.fieldnames.metadata];

%% Define HAVOK__ struct
config.havok__.plots = {'phaseY','phaseV','sing','conteig','reconstructV','rmseV','matrix'};
config.havok__.fieldnames.input = {'algorithm','system','params','x0',...
    'dt','timesteps','horizon','rank','delays','spacing','measured','observables'};
config.havok__.fieldnames.svd = {'U_','s_','sn','sn_','V_'};
config.havok__.fieldnames.hankel = {'H'};
config.havok__.fieldnames.model = {'A','B','omega','d','Vtrain','Vr','tr','RMSEVr','rmseVr','Vtest','Vp','tp','RMSEVp','rmseVp',...
    'RMSEV','rmseV'};

config.havok__.fieldnames.order = [config.havok__.fieldnames.input,config.general.fieldnames.data,...
    config.havok__.fieldnames.hankel,config.havok__.fieldnames.svd,config.havok__.fieldnames.model,...
    config.general.fieldnames.metadata];

%% Define HAVOK___ struct
config.havok___.plots = {'phaseY','phaseV','sing','conteig','reconstructV','rmseV','matrix'};
config.havok___.fieldnames.input = {'algorithm','system','params','x0',...
    'dt','timesteps','horizon','rank','delays','spacing','measured','observables'};
config.havok___.fieldnames.svd = {'U_','s_','sn','sn_','V_'};
config.havok___.fieldnames.hankel = {'H'};
config.havok___.fieldnames.model = {'A','B','omega','d','Vtrain','Vr','tr','RMSEVr','rmseVr','Vtest','Vp','tp','RMSEVp','rmseVp',...
    'RMSEV','rmseV'};

config.havok___.fieldnames.order = [config.havok___.fieldnames.input,config.general.fieldnames.data,...
    config.havok___.fieldnames.hankel,config.havok___.fieldnames.svd,config.havok___.fieldnames.model,...
    config.general.fieldnames.metadata];

%% Define HAVOKc struct % TODO
config.havokc.plots = {'phaseY','phaseV','sing','conteig','reconstructV','rmseV','matrix'};
config.havokc.fieldnames.input = {'algorithm','system','params','x0','input',...
    'dt','timesteps','horizon','rank','delays','spacing','measured','observables'};
config.havokc.fieldnames.svd = {'U_','s_','sn','sn_','V_'};
config.havokc.fieldnames.data = {'U'};
config.havokc.fieldnames.hankel = {'H','Hu'};
config.havokc.fieldnames.model = {'A','B','omega','Vtrain','Vr','tr','RMSEVr','rmseVr','Vtest','Vp','tp','RMSEVp','rmseVp',...
    'RMSEV','rmseV'};

config.havokc.fieldnames.order = [config.havokc.fieldnames.input,config.general.fieldnames.data,...
    config.havokc.fieldnames.data,config.havokc.fieldnames.hankel,config.havokc.fieldnames.svd,...
    config.havokc.fieldnames.model,config.general.fieldnames.metadata];

%% Define CONVCOORD struct
config.convcoord.plots = {'phaseY','phaseV','sing','reconstructW','rmseW','matrix'};
config.convcoord.fieldnames.input = {'algorithm','system','params','x0',...
    'dt','timesteps','horizon','rank','delays','spacing','measured','observables'};
config.convcoord.fieldnames.svd = {'U_','s_','sn','sn_','V_'};
config.convcoord.fieldnames.hankel = {'H'};
config.convcoord.fieldnames.model = {'A','Wtrain','Wr','tr','RMSEWr','rmseWr','Wtest','Wp','tp','RMSEWp','rmseWp','RMSEW','rmseW'};

config.convcoord.fieldnames.order = [config.convcoord.fieldnames.input,config.general.fieldnames.data,...
    config.convcoord.fieldnames.hankel,config.convcoord.fieldnames.svd,config.convcoord.fieldnames.model,...
    config.general.fieldnames.metadata];

%% Set latex as plot interpreter
set(groot,'defaultTextInterpreter','latex');
set(groot,'defaultAxesTickLabelInterpreter','latex');
set(groot,'defaultLegendInterpreter','latex');

%% Set general plot config
% set(groot,'defaultAxesGridLineStyle','--');
% set(groot,'defaultAxesGridAlpha',0.2);
% set(groot,'defaultAxesGridColor',[0.1 0.1 0.1]);
set(groot,'defaultAxesFontSize',14);
set(groot,'defaultLineLineWidth',1);

end


